### ISSUE TITLE
are you sharing screenshots of the spamming i did to your pathetic woke friends?

### ISSUE THREAD

**Issue by ghost** [octanuary/GoAnimate-Archive#101]
because if you are, then screenshot this! hi, i have something for you...
![GVcSoz-XYAAiKeA](https://github.com/user-attachments/assets/27443ba9-8326-4d22-981d-e950f5086518)

**Comment by octanuary** [comment]
> i have something for you...

if it's not kim wexler's feet i don't want it

**Comment by ghost** [comment]
haha really funny, that almost sounds like **a certain someone** who groomed you would say
*̶c̶o̶u̶g̶h̶*̶ ̶b̶e̶n̶s̶o̶n̶ ̶*̶c̶o̶u̶g̶h̶*̶
never mind, i'm probably just misremembering...

**Comment by octanuary** [comment]
dude i don't even know benson he's been gone for over 3 years
i think you may have issues

**Comment by ghost** [comment]
oh i have issues? well look at your pfp, doesn't that say the name about you?

**Comment by octanuary** [comment]
my pfp? what about it
i think it's a nice design
unless there's something aesthetically wrong about it you're trying to point out

**Comment by octanuary** [comment]
is it off center or something?

**Comment by ghost** [comment]
no but take a wild/obvious guess what i think is wrong with it

**Comment by ghost** [comment]
plus, are we going talk things out or are you just going to joke around and send gifs that have no fucking meaning whatsoever in my view?

**Comment by octanuary** [comment]
> no but take a wild/obvious guess what i think is wrong with it

i don't know... there is one thing i can think of, but you seem too much of a kindhearted individual that that couldn't possibly be an issue to you

**Comment by ghost** [comment]
> > no but take a wild/obvious guess what i think is wrong with it
> 
> i don't know... there is one thing i can think of, but you seem too much of a kindhearted individual that that couldn't possibly be an issue to you

i'm fine with it, it's just the specific symbolism of the middle line that i don't support. is that an issue to you?
