### ISSUE TITLE
i can keep going until you take action without any of your snarky-ass responses

### ISSUE THREAD

**Issue by Drew-Pickles** [octanuary/GoAnimate-Archive#5]
you can't stop me, fag boy

**Comment by octanuary** [comment]
aww thanks 😊

**Comment by Drew-Pickles** [comment]
your welcome, tryhard

**Comment by Drew-Pickles** [comment]
oh and nice pfp, did your intolerant-left brain tell you to update it?

**Comment by octanuary** [comment]
![hawk-tuah-hawktuak](https://github.com/user-attachments/assets/083a1aeb-eca7-44cd-83dd-f14a8e141722)

**Comment by Drew-Pickles** [comment]
like i said "the 'People who be DESPERATE for attention' is you and your woketard friends that claim to be "apolitical" and yet YA'LL WROTE YOUR FUCKING MENTAL ILLNESS IN THE GOD DAMN BIO."

**Comment by octanuary** [comment]
1. wtf are you even talking about like who are you
2. erm actually it's "y'all", "ya'll"

**Comment by Drew-Pickles** [comment]
1. look at the very first issue i used posted and i'm not telling you.
2. whatever, it's just a fucking grammar error.
